create the hugo file with the correct title

diff --git a/module1_task1/Makefile b/module1_task1/Makefile
--- a/module1_task1/Makefile
+++ b/module1_task1/Makefile
@@ -3,4 +3,13 @@ build:
 clean:
 	rm -rf dist/
 post:
-	hugo new posts/${POST_TITLE}.md
+	@if [ -z "$(POST_NAME)" ]; then \
+		echo "Error: POST_NAME environment variable is not set."; \
+		exit 1; \
+	fi
+	@if [ -z "$(POST_TITLE)" ]; then \
+		echo "Error: POST_TITLE environment variable is not set."; \
+		exit 1; \
+	fi
+	echo "---\ntitle: \"$(POST_TITLE)\"\ndate: `date -Iseconds`\ndraft: true\n---\n" > content/posts/$(POST_NAME).md
+
